version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      S3_REGION_NAME: ${S3_REGION_NAME}
      PHOTO_S3_BUCKET: ${PHOTO_S3_BUCKET}
      RUNPOD_API_KEY: ${RUNPOD_API_KEY}
      RUNPOD_GEMMA_BASE_URL: ${RUNPOD_GEMMA_BASE_URL}
      RUNPOD_GEMMA_MODEL: ${RUNPOD_GEMMA_MODEL}
      GEMMA_MAX_TOKENS: ${GEMMA_MAX_TOKENS}
      RUNPOD_LLAVA_BASE_URL: ${RUNPOD_LLAVA_BASE_URL}
      RUNPOD_LLAVA_MODEL: ${RUNPOD_LLAVA_MODEL}
      LLAVA_MAX_TOKENS: ${LLAVA_MAX_TOKENS}
    volumes:
      - .:/app
